# fly.toml app configuration file generated for consolee on 2023-11-03T11:32:04Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "consolee"
primary_region = "ams"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
